matrix:
  include:
    - language: python
      python: 3.5
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover

    - language: r
      r:
        - oldrel
        - release
      cache: packages
      before_script:
        - cd dashboard
      install:
        - R -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("dashboard")'
      script:
        - R -e "devtools::test()"

notifications:
  email:
    - g.w.mika@gmail.com